### ISSUE TITLE
ExpressLRS

### ISSUE THREAD

**Issue by SZ-MXK** [AlessandroAU/ExpressLRS#1]
Hi，

**Comment by AlessandroAU** [comment]
Sure, we can have a chat. Join on discord? 
https://discord.gg/dS6ReFY

**Comment by SZ-MXK** [comment]
I can't use discord，Do you use Facebook? +86 18818594513

**Comment by AlessandroAU** [comment]
Did some testing of the system on the weekend, still have some issues. Much shorter than expected range. Not sure why. Perhaps preamble too short.

**Comment by SZ-MXK** [comment]
https://github.com/RavenLRS/raven I've tested this LRS, which can reach 5 kilometers. If the distance is short, you may need to redesign the hardware

**Comment by AlessandroAU** [comment]
I don't think it is a hardware problem, I am using self contained modules for the radio interface.

**Comment by AlessandroAU** [comment]
Range issues fixed
