### ISSUE TITLE
wrong roll, pitch value transmitted for 10ms

### ISSUE THREAD

**Issue by adrianmiriuta** [AlessandroAU/ExpressLRS#101]
@AlessandroAU 

in a 10 minute flight i had three twitches ...
bad input signal values in roll and pitch (always about 10 ms) 
my firmware is for R9M tx, R9MM rx, is compiled with EU freq band, and 3 pos switches.

![Screenshot from 2020-06-14 20-22-32](https://user-images.githubusercontent.com/29194202/84601036-cf487a00-ae7d-11ea-8c21-00c08cbe6295.png)
![Screenshot from 2020-06-14 20-22-22](https://user-images.githubusercontent.com/29194202/84601037-cfe11080-ae7d-11ea-9b83-e06ada5106e9.png)
![Screenshot from 2020-06-14 20-21-55](https://user-images.githubusercontent.com/29194202/84601039-d079a700-ae7d-11ea-9d66-968f8abd3ad1.png)
![Screenshot from 2020-06-14 20-21-37](https://user-images.githubusercontent.com/29194202/84601040-d079a700-ae7d-11ea-8d74-2da03a3ec8cf.png)

**Comment by JyeSmith** [comment]
Hi @adrianmiriuta can you please upload the log file.

**Comment by adrianmiriuta** [comment]
@JyeSmith 

Hi Jye ,
attached config and log file.

[R9M_twitches.zip](https://github.com/AlessandroAU/ExpressLRS/files/4778439/R9M_twitches.zip)

**Comment by JyeSmith** [comment]
Thanks @adrianmiriuta 

This is CF?  What debug was used?

**Comment by adrianmiriuta** [comment]
@JyeSmith

debug_mode = ANGLERATE

you can see the settings in the diff file.

**Comment by JyeSmith** [comment]
This is really weird and not something I have seen or felt in flight.  If it was spurious data I would expect it to affect all channels.  It is unlikely bad data from ExLRS since every packet has a CRC.

What gimbals are you using on the handset?  I know that I have had issues with slow response on hall gimbals caused by a bad connection.  But this looks different again.

**Comment by adrianmiriuta** [comment]
@JyeSmith

clarification
I had the resistor mod like described in the rcgroups

![FrSky R9M (2018 model) resistor mod](https://user-images.githubusercontent.com/29194202/84631391-9516c100-aeed-11ea-981c-d5a203f8443d.png)

I removed it because I got "Telemetry lost from my Taranis X9D plus"
and you said it is not intended for the X9D
and I got these twitches !
on my first flights with the resistor I didn't had them !

I have the  hall gimbals for  the Taranis.

**Comment by JyeSmith** [comment]
Just checking, did you change the baud rate back to 115200?

Are you in the discord chat?  Might be easier to trouble shoot in there.

**Comment by adrianmiriuta** [comment]
@JyeSmith

1. no (I use the TBS release of OPENTX  with CRSFshot fir X9D plus)
 I didn't find where to change serial speed!

2. no

**Comment by adrianmiriuta** [comment]
@JyeSmith

I put the pullup resistor back in place, it does seem not to happen any more.
I have to fly a few packs to make sure.

br. adrian

**Comment by AlessandroAU** [comment]
I think there has been some confusion. 

The X9D will do 400k and does not allow setting to 115200 baud. (AFAIK)
The QX7 cannot do 400k without the inverter mod, but it allows you to switch between 115200/400000.

The R9M module cannot do 400k without resistor mod.
Therefore, to use R9M at 400k with X9D requires the resistor mod

**Comment by adrianmiriuta** [comment]
@AlessandroAU 
Thx.
