### ISSUE TITLE
[Testing Required] 2.4GHz Tx PCB

### ISSUE THREAD

**Issue by JyeSmith** [AlessandroAU/ExpressLRS#123]
https://easyeda.com/jyesmith/expresslrs-tx-sx1280

This is v2 and currently untested. BUT if you are willing to test and trouble shoot any issues feel free to order some.  Jump on the discord chat and let us know how you go :)

Once tested this issue will be closed and a PR made.  So if you want plug and play best to wait until then.

5v buck reg https://a.aliexpress.com/_dZQNQ3v

**Comment by JBKingdon** [comment]
Awesome, can you add a link to the buck converter you used, it looks like it has an unusual pinout, maybe enable/Vbat/gnd/Vout ?
