### ISSUE TITLE
R9MM + MINI Not syncing on first boot. starting in bootloader

### ISSUE THREAD

**Issue by l2smith2** [AlessandroAU/ExpressLRS#149]
latest master branch flashed. 14/8/20
R9 RX's start directly into bootloader mode on first power up. power cycling they sync with radio.

**Comment by cruwaller** [comment]
Sorry for late reply!
R9MM bootloader is updated (PR #206 ) lately and maybe you can try to update latest version.

**Comment by AlessandroAU** [comment]
@l2smith2 did you have a chance to test the fix?

**Comment by l2smith2** [comment]
I haven't tested the new bootloader. It seems the problem is most prominent
on quads with a large capacitor

**Comment by gretel** [comment]
noticed the panasonic caps i use can take a couple of seconds to loose charge - which i have to wait in case.

**Comment by l2smith2** [comment]
It's fine once the caps are charged. Just the initial power up causes the
problem

**Comment by gretel** [comment]
ah nevermind i was refering to the time it takes until it resets properly..

**Comment by gretel** [comment]
seems robust now - have been flashing the recent bootloaders.

**Comment by AlessandroAU** [comment]
Thanks for checking @gretel 👍
