### ISSUE TITLE
EBYTE E32 module support

### ISSUE THREAD

**Issue by axife** [AlessandroAU/ExpressLRS#151]
These modules available on AliExpress for $5-10
They are based on SX1276 or SX1278 and STM8L0

QCZEK already did a close source firmware to make LRS from these modules.

**Comment by JyeSmith** [comment]
Im not sure the stm8 will be powerful enough and at only 16MHz.  @peho-nordic has done some work with the STM32L071 (32MHz) and may be able to comment further.

**Comment by JBKingdon** [comment]
Hi Jye - where did you find info on the cpu in the e32? I couldn't see anything about it in Ebyte's doc

**Comment by axife** [comment]
QCZEK did LRS based on eByte. It is close source.
http://qczek.beyondrc.com/qczek-lrs-433mhz-1w-lora-rc-link/
> And finally i found E32-TTL-1W serial rf link based on LORA SX1278 spread
spectrum RF chip, and stm8L MCU, which would be re flashed by my firmware.

There are more references but I can't find right now. Possibly exact STM8L0
model is shown in YouTube video when someone flashes eByte

**Comment by AlessandroAU** [comment]
It may be possible, but that chip is tiny, slow and doesn't have much flash space.

**Comment by JyeSmith** [comment]
@JBKingdon the user manual states STM8L MCU.  Its either not going to work, or the amount of time to make it function isnt worth it.  These are used on VTxs and have bugger all space.

**Comment by cruwaller** [comment]
I think it would be possible to get that working but requires lot of optimizations and simplifications.
And I guess you cannot get full benefit of ELRS to working with so small MCU.

**Comment by AlessandroAU** [comment]
I think STM8 would be to limited to support the current features
