### ISSUE TITLE
Esp-01 support as RX?

### ISSUE THREAD

**Issue by annoyinganime** [AlessandroAU/ExpressLRS#179]
It is really easy to solder onto SOT-8 pins of built-in SPI flash, and GPIO pins from pinheader can be used for NSS and RST on LoRa. I don't really need LEDs, but if I remember correctly, ESP-01 has one onboard. So, is there a way to share built-in flash SPI bus to connect SX127x, or it will make program flash very slow to the point when it becomes unusable? And what pins are used to communicate with SX127x other than SPI?

**Comment by AlessandroAU** [comment]
You can't share the SPI afaik. Just get an esp01f 👍
