### ISSUE TITLE
Hardware compatibility with R9M Lite?

### ISSUE THREAD

**Issue by pablogranolabar** [AlessandroAU/ExpressLRS#189]
Hi,

Can the Frsky R9M Lite 2019 module be flashed with ExpressLRS? I am trying to use ExpressLRS with a TBS Tango 2 w/ PCB v3 + module bay upgrade.

TIA

**Comment by pablogranolabar** [comment]
Never mind just saw the link.

**Comment by AlessandroAU** [comment]
Yes this should work, just be warned, one of the devs has recently discovered that the tango only updates RC data on the external module at 50hz. Hopefully TBS will fix this soon...
