### ISSUE TITLE
Any performance results from LoRAWAN mesh?

### ISSUE THREAD

**Issue by pablogranolabar** [AlessandroAU/ExpressLRS#192]
Hi,

Have you done any type of experimentation with LoRAWAN mesh? What type of performance characteristics could be expected with a mesh type topology for swarm applications?

Regards

**Comment by AlessandroAU** [comment]
We not are using a LoRa stack or LoRaWAN, This is a point to point protocol that uses LoRa modulation to send packets. I can't comment on any mesh or swam applications as I have no idea.
