### ISSUE TITLE
R9MX pinout

### ISSUE THREAD

**Issue by norulers** [AlessandroAU/ExpressLRS#195]
R9mx flash expresslrs. Can someone tell me the pin of crsf? Thank you very much

**Comment by AlessandroAU** [comment]
Did you find it? I think there's an image on the wiki

**Comment by norulers** [comment]
> Did you find it? I think there's an image on the wiki

Thank you. I've found it   CH2(PA9,TX)  CH3(PA10,RX)

**Comment by norulers** [comment]
Thank you. I've found it&nbsp; &nbsp;CH2(PA9,TX)&nbsp; CH3(PA10,RX)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlessandroAU/ExpressLRS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 中午1:21
收件人:&nbsp;"AlessandroAU/ExpressLRS"<ExpressLRS@noreply.github.com&gt;;
抄送:&nbsp;"norulers"<norulers@vip.qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [AlessandroAU/ExpressLRS] R9MX pinout (#195)





 
Did you find it? I think there's an image on the wiki
