### ISSUE TITLE
Prevent rx/tx link when switch mode is different

### ISSUE THREAD

**Issue by JBKingdon** [AlessandroAU/ExpressLRS#218]
Currently there is nothing to prevent a tx and rx compiled with different switch modes from connecting, and since the switch positions will be mis-interpreter this is potentially dangerous as it could lead to unintentional arming.

Not sure how to implement this with the available bits - is there any space in the sync packet to indicate the switch mode? If not, we could change the caeser on the crc based on the switch mode which would be enough to at least reduce the probability of connection to a very low level.

**Comment by nangel0** [comment]
And if we implement the openTx model binding number?

Not sure how it works, but tbs implemented it recently.

**Comment by AlessandroAU** [comment]
Yeah I agree, needed safety feature. I think there's room in the sync packet.

**Comment by cruwaller** [comment]
this is fixed already so closing now.
