### ISSUE TITLE
link issues

### ISSUE THREAD

**Issue by awright424** [AlessandroAU/ExpressLRS#223]
I have a 2018 r9m, accst vesrsion, and a r9mm-ota access receiver. I have successfully flashed both and just went through again to make sure that everything is the same for userdefines when flashed. I do not know if this is an issue with the hardware I chose being incompatible but initially this morning after turning my radio on first and then turning the quad on II was able to get a good link for about 5 minutes before I started having the drops. I am sitting here typing this with my radio not far from the receiver and have no connection. I am not sure what is going on. I have a video showing some of the issues I had: https://www.youtube.com/watch?v=ZwWq6rrEEis&feature=youtu.be 
https://www.youtube.com/watch?v=9zAYon2IZm4&feature=youtu.be
two videos explain the situation.

**Comment by AlessandroAU** [comment]
Something definitely wrong, what setting have you selected in LUA, are they default? Did you do the resistor mod?

**Comment by JBKingdon** [comment]
Hi @awright424 
You might want to hop onto our Discord server if you haven't already. It's a bit chaotic but they're a friendly bunch and will do what they can to help. There's a lot of people that have recently setup R9 gear on there at the moment so the chances are that someone will have seen a similar problem.

https://discord.gg/dS6ReFY

**Comment by awright424** [comment]
> Something definitely wrong, what setting have you selected in LUA, are they default? Did you do the resistor mod?
> 
> EDIT: Would be good to check the communication between Radio and TX is good, in the upper right of the LUA script display you should see some numbers, eg 0:200. What are yours?

the lua script doesnt seem to indicate good packet health at all. I have seen it show 1:0 which was weird.

**Comment by AlessandroAU** [comment]
that is not good, did you do the resistor mod?

**Comment by awright424** [comment]
> that is not good, did you do the resistor mod?

no resistor mod as of yet. I need to look and hope I have resistors laying around that will work otherwise its order and wait.

**Comment by AlessandroAU** [comment]
Do you have values show up in the LUA script?

**Comment by awright424** [comment]
> Do you have values show up in the LUA script?

![20201122_105201](https://user-images.githubusercontent.com/2151230/99908479-e0a97400-2cb0-11eb-9b5b-75ce0eddf9f7.jpg)
![20201122_105158](https://user-images.githubusercontent.com/2151230/99908481-e56e2800-2cb0-11eb-8073-1798d72fb3d1.jpg)

**Comment by AlessandroAU** [comment]
That looks fine, are you still getting dropouts? Can you scan for sensors and show telemetry?

**Comment by awright424** [comment]
its gaining and losing telemetry after connecting with a solid link for 4 minutes. 

https://youtu.be/S5bVk5LVeTE

i have two 470ohm resistors so gonna try the resistor mod now

**Comment by AlessandroAU** [comment]
Looks like a UART comms issue to me, the resistor mod should fix it. A single 470ohm resistor should be fine

**Comment by awright424** [comment]
well i got the resistor soldered on then when attempting to put the case together broke the pad off the inverter. this module might be done for. ordered another of the 2018 versions for 10 bucks

**Comment by AlessandroAU** [comment]
It might be recoverable, post a picture of which pad got damaged.

**Comment by awright424** [comment]
![20201124_044840](https://user-images.githubusercontent.com/2151230/100077740-b4a50480-2e10-11eb-9a9d-a2483a46fccd.jpg)
you cacan see the pad on the inverter. soldering to the smd resistor was fine. board turns on but no communication with the radio.

**Comment by AlessandroAU** [comment]
Is the tab of the transistor broken? It's possible to bridge to the resistor next to it, do you have a hot-air station?

**Comment by awright424** [comment]
> Is the tab of the transistor broken? It's possible to bridge to the resistor next to it, do you have a hot-air station?

no I do not. you mean where r3 is silk screened? i can try with a regular iron but i doubt it will work. hoping to have my replacement come Wednesday

**Comment by AlessandroAU** [comment]
If you're up to it, you can replace the transistor you broke with one of these I highlighted in green (we don't use them) 

![r9m_backpack_pins_trans](https://user-images.githubusercontent.com/22009829/100093918-edda8480-2ea3-11eb-8380-33a3093a29fb.jpg)

**Comment by awright424** [comment]
so i moved the resistor with j6. i then soldered the 3.3v connector to the arm of the resistor. is that correct?

**Comment by AlessandroAU** [comment]
Top of transistor goes to top of R3 with the extra resistor between those two and 3.3v. Can you send pic?

**Comment by awright424** [comment]
i see what i did wrong. i have no connection to r3.

![Uploading 16062262238375351236562582478654.jpg…]()

**Comment by awright424** [comment]
looks like its working now. i can get the lua script to show data. did a pull compiling and flashing the tx and rx to be safe

**Comment by AlessandroAU** [comment]
Nice!

**Comment by awright424** [comment]
![20201124_092126](https://user-images.githubusercontent.com/2151230/100106431-8803e380-2e36-11eb-973f-f0205fe486f4.jpg)
![20201124_092117](https://user-images.githubusercontent.com/2151230/100106456-8fc38800-2e36-11eb-9aed-cf9ea7b92426.jpg)
![20201124_092149](https://user-images.githubusercontent.com/2151230/100106493-994cf000-2e36-11eb-9dc8-c19d7e66d5d9.jpg)
thank you for the great work and excellent response time. you saved me from having to buy a tbs tracer and i didnt have to spend more money. i did buy another 2018 r9m but at 10 dollars its good to have a backup. thanks again for the help and the great project. not once have i lost signal or telemetry while testing so far

**Comment by AlessandroAU** [comment]
Happy flying 👍

**Comment by JBKingdon** [comment]
Hey, well done! Glad you got it going.

**Comment by arfk9919** [comment]
I want to ask if there is an alternative to the transistor that I marked is damaged
![20230303_235642](https://user-images.githubusercontent.com/126906193/222798500-e5ebd86d-07b8-43b1-a9b4-da30d86b8a64.jpg)
