### ISSUE TITLE
TTGO LORA32 V2.0 Signal Range

### ISSUE THREAD

**Issue by alexvazquez** [AlessandroAU/ExpressLRS#235]
Im going to build my receiver using the TTGO LORA32 V2.0, how does this can be compared with the range of Frsky RM9 module? Am I going to get same strenght of signal for long range as in RM9 module? Appreciate it

**Comment by AlessandroAU** [comment]
That module is only ~50mw so much less power than the R9M, it will be fine for medium range maybe flying. 50hz mode will still go 10km+ if antennas are decent
