### ISSUE TITLE
Troubleshooting data on WiFi page or FTDI serial for DIY receivers

### ISSUE THREAD

**Issue by FireNWater** [AlessandroAU/ExpressLRS#236]
For those of us hand building DIY ExLRS receivers, I believe it is a given that we may introduce (ahem) QC issues into our hardware during the production process.

To assist in troubleshooting, I would like to be able to obtain feedback from the receiver itself thru either the WiFi web page, or serial link using PuTTY or similar software.

Parameters I would like to see are:

-ESP-01F health (Admittedly may be unnecessary if you’re getting the web page)
-RF link status and channel values. 
-Link status with the SX1280 chip. 
-Any other info the ESP can give us to help troubleshooting.

Thanks!

**Comment by JyeSmith** [comment]
With all receivers once connected to a FC and configured, use Upload & Monitor in PFIO to see the serial output.  This will give you everything listed above.
