### ISSUE TITLE
OpenTX fw for Jumper T18

### ISSUE THREAD

**Issue by peelerj** [AlessandroAU/ExpressLRS#258]
Could there possibly be an OpenTX fw compiled to use with the Jumper T18 radio??? I see there are some for Jumper T16s...etc. thanks.  It has the 5in1 radio module.   Which includes support for r9...

**Comment by peelerj** [comment]
opentx-t18-2.3.11.bin worked with the Jumper T18!  If you could put it in the the opentx folder would be great!
Thanks!

**Comment by FLY-CODE77** [comment]
Where cab i get2.÷.11 !??

**Comment by peelerj** [comment]
It was put into the discord  #general board by @peho.  I downloaded it from
there.  I have asked them to put one in the opentx folder.
