### ISSUE TITLE
Link to Mini 900MHz RX files not working

### ISSUE THREAD

**Issue by darwinfpv** [AlessandroAU/ExpressLRS#315]
The link to the Mini 900MHz RX files is not working, any help? thanks

**Comment by AlessandroAU** [comment]
We moved the folders around and forgot to update the readme, you can find the designs under the /PCB/900MHZ folder https://github.com/AlessandroAU/ExpressLRS/tree/master/PCB/900MHz

**Comment by darwinfpv** [comment]
Thank you very much 🙌
