### ISSUE TITLE
I want to know the author's email address

### ISSUE THREAD

**Issue by ORangeCaptain** [AlessandroAU/ExpressLRS#320]
I will provide a module of esp32 and sx1276 to the author. I have connected 0.96 OLED and a five way button. I want to integrate Lua on the remote control into the high frequency head, and use the OLED screen to modify the ELRS parameters.

**Comment by NiklasVoigt** [comment]
http://discord.gg/dS6ReFY

**Comment by ORangeCaptain** [comment]
> http://discord.gg/dS6ReFY

Thank you.

**Comment by NiklasVoigt** [comment]
@ORangeCaptain I think this is not an Issue and can be closed.
