### ISSUE TITLE
More cleanup in ESP32uartTask

### ISSUE THREAD

**Issue by JBKingdon** [AlessandroAU/ExpressLRS#87]
I noticed a couple of opportunities for improvements in ESP32uartTask and left some comments (didn't want to pollute the PR I was working on with unrelated changes)

**Comment by AlessandroAU** [comment]
Yep I saw those, we can implement them. Same here as I just merged in something I knew was working when we tried to fix those crashes.

**Comment by AlessandroAU** [comment]
Where are the comments? I saw them in a PR but I'm can't find them right now.

**Comment by JBKingdon** [comment]
Cool. I should update https://github.com/AlessandroAU/ExpressLRS/pull/86 to remove the comments and fix any merge conflict

**Comment by AlessandroAU** [comment]
Oh whoops sorry I didn't mean to break your PR! I will test the PR on r9m and fix the conflict tomorrow :)

**Comment by JBKingdon** [comment]
I think we covered this, closing.
