### ISSUE TITLE
433 MHz HW compatibility

### ISSUE THREAD

**Issue by Unb9rn** [AlessandroAU/ExpressLRS#94]
Hello! Is it compatible with the same Lilygo TTGO ESP32 modules but with 433MHz module?
Like [that](https://aliexpress.ru/item/32846302183.html) one?

**Comment by AlessandroAU** [comment]
This should work fine, although be warned, I have not tested 433mhz for quite some time.

**Comment by Unb9rn** [comment]
Well, I think I'll find out =) Thanks!
