### ISSUE TITLE
 It would be possible to compile in stm32F0 ?

### ISSUE THREAD

**Issue by JesusGonfer** [AlessandroAU/ExpressLRS#97]
Would it be possible to compile this code (rx) in stm32f030f4p6?
Very small receivers could be developed at very low cost

**Comment by AlessandroAU** [comment]
I think it will work, we just need 1 timer and 1 SPI and 1 UART.

**Comment by JesusGonfer** [comment]
it seems that it will be compatible although its capacity may be a problem

**Comment by AlessandroAU** [comment]
Yeah, seems we are a little over in flash 
![image](https://user-images.githubusercontent.com/22009829/84237435-b027b080-ab3c-11ea-94d2-ea38997a0dc8.png)
